dix/events.c: add missing prototype
Prevent this warning:
../../dix/events.c: In function ‘WindowsRestructured’:
../../dix/events.c:2255:12: warning: implicit declaration of function ‘CheckMotion’; did you mean ‘CheckExtension’? [-Wimplicit-function-declaration]
 2255 |     (void) CheckMotion((xEvent *)NULL);